name: Docs

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/docs.yml'
      - 'docs_src/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build
        run: cd docs_src && npm ci && npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_src/__DOCS__/dist/svelte-rip
